# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Docker Image to Heroku App
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${HEROKU_EMAIL}
          # Heroku Dyno Formation
          formation: botcalendar
          # Your Heroku API Key
          api_key: ${HEROKU_APIKEY}
          # Your Heroku App Name
          app_name: ${HEROKU_APP_NAME}
          # Dokerfile path
          dockerfile_path: .

